# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3deploy < Formula
  desc "Deploy static websites to Amazon S3 with Gzip and headers support."
  homepage "https://github.com/bep/s3deploy"
  version "2.8.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bep/s3deploy/releases/download/v2.8.1/s3deploy_2.8.1_macOS-ARM64.tar.gz"
      sha256 "f5fe1b846a21dc0ee6c97ffd5bf177d2db460ae153652c0bcaedf915b13f3886"

      def install
        bin.install "s3deploy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bep/s3deploy/releases/download/v2.8.1/s3deploy_2.8.1_macOS-64bit.tar.gz"
      sha256 "bde17115c198065a7e0a45f9f302bfc9b013d5729406fdbac7ad8c6f70c017da"

      def install
        bin.install "s3deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bep/s3deploy/releases/download/v2.8.1/s3deploy_2.8.1_Linux-ARM.tar.gz"
      sha256 "87d3f225f3f6b3ae3f44ead9a277a7848abd36522388a814ce32b7009829f8b7"

      def install
        bin.install "s3deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bep/s3deploy/releases/download/v2.8.1/s3deploy_2.8.1_Linux-ARM64.tar.gz"
      sha256 "9e643e83d7240d17c8e34504855c26045a1f926158fed2db46baf5d0bf9914f4"

      def install
        bin.install "s3deploy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bep/s3deploy/releases/download/v2.8.1/s3deploy_2.8.1_Linux-64bit.tar.gz"
      sha256 "3e87e682b75d8a57e42a2a73209a4299d954ebb8f00c010b97d87246564ec328"

      def install
        bin.install "s3deploy"
      end
    end
  end

  test do
    system "#{bin}/s3deploy", "-h"
  end
end
