# This file was generated by GoReleaser. DO NOT EDIT.
class S3deploy < Formula
  desc "Deploy static websites to Amazon S3 with Gzip and headers support."
  homepage "https://github.com/bep/s3deploy"
  url "https://github.com/bep/s3deploy/releases/download/v2.3.5/s3deploy_2.3.5_macOS-64bit.tar.gz"
  version "2.3.5"
  sha256 "99aed5eaef27c98b5de659bab1f9db554abe62e0e9fade7dfd160c8aeeebe99f"

  def install
    bin.install "s3deploy"
  end

  test do
    system "#{bin}/s3deploy", "-h"
  end
end
